name: Decrypt repository
description: Installs git-crypt and unlocks the repository
author: Gabriel Pereyra
inputs:
  GIT_CRYPT_KEY:
    description: Key for unlock git-crypt
    required: true

# How to generate the GIT_CRYPT_KEY?
#
# Step 1: export and encode your git-crypt key by using the command:
# git-crypt export-key ./tmp-key && cat ./tmp-key | base64 | pbcopy && rm ./tmp-key
#
# Step 2: add the output as a repository secret with the name GIT_CRYPT_KEY
#
# acknowledgements: https://github.com/marketplace/actions/github-action-to-unlock-git-crypt-secrets

runs:
  using: "composite"
  steps:
    - name: Install git-crypt
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          git clone https://github.com/AGWA/git-crypt.git
          cd git-crypt && make && make install PREFIX=/opt/project
          echo "/opt/project/bin" >> $GITHUB_PATH
        else
          brew install git-crypt
        fi
      shell: bash

    - name: Unlock git-crypt
      run: |
        echo "${{ inputs.GIT_CRYPT_KEY }}" | base64 -d > ./git-crypt-key
        git-crypt unlock ./git-crypt-key && echo "success"
        rm ./git-crypt-key
      shell: bash