name: Static code analysis

on:
  pull_request:
    branches: [ "develop", "main" ]
    types: [ "opened", "synchronize", "reopened", "ready_for_review"]

jobs:
  build:
    name: Detekt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get environment ready
        uses: ./.github/actions/get-env-ready

      - name: Decrypt repo
        uses: ./.github/actions/decrypt-repo
        with:
          GIT_CRYPT_KEY: "${{ secrets.GIT_CRYPT_KEY }}"

      - name: Build and run detekt
        run: ./gradlew detekt