name: Snapshot

on:
  workflow_dispatch:
    inputs:
      testers:
        description: "Email testers, should be separated with a comma (e.g. pereyrarg11@gmail.com, gabriel.pereyra@sondermut.com)"
      # required: true
        default: ""

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: oracle
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assemble # TODO: change to assembleRelease when signing is configured

    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        format: "YYYY-MM-DDTHH-mm"
        utcOffset: "-06:00"

    - name: Upload apk
      uses: actions/upload-artifact@v3
      with:
        name: "snapshot_${{ steps.current-time.outputs.formattedTime }}"
        path: "./app/build/outputs/apk/debug/*.apk"
        if-no-files-found: error

    # TODO: distribuite APK through Firebase App Distribution
