name: Snapshot

on:
  workflow_dispatch:
    inputs:
      build_variant:
        description: 'Build variant'
        required: true
        default: 'Release'
        type: choice
        options:
          - Debug
          - Release

jobs:
  build:
    name: Generate snapshot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get environment ready
        uses: ./.github/actions/get-env-ready

      - name: Decrypt repo
        uses: ./.github/actions/decrypt-repo
        with:
          GIT_CRYPT_KEY: "${{ secrets.GIT_CRYPT_KEY }}"

      - name: Build APK
        uses: ./.github/actions/build-apk
        with:
          BUILD_VARIANT: "${{ inputs.build_variant }}"

      - name: Distribute APK
        uses: ./.github/actions/distribute-apk
        with:
          PREFIX: "snapshot"