name: Weekly build
on:
  schedule:
    - cron: '00 14 * * 1'

jobs:
  weekly_build:
    name: Build and distribute APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get environment ready
        uses: ./.github/actions/get-env-ready

      - name: Build APK
        uses: ./.github/actions/build-apk
        with:
          BUILD_VARIANT: "Release"

      - name: Distribute APK
        uses: ./.github/actions/distribute-apk
        with:
          PREFIX: "weekly"